# Generated by Django 2.0.7 on 2018-12-01 16:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('924906e2-f588-11e8-b8a5-14109fdfa251')),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 1, 16, 45, 55, 341855)),
        ),
    ]
