# Generated by Django 2.0.7 on 2018-12-01 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20181201_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 1, 16, 46, 54, 419872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b57f9c98-f588-11e8-b62e-14109fdfa251')),
        ),
    ]
