# Generated by Django 2.0.7 on 2018-12-02 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20181201_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 5, 26, 52, 421267, tzinfo=utc)),
        ),
    ]
