# Generated by Django 2.1.5 on 2019-02-03 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20181206_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 4, 6, 48, 25, 82947, tzinfo=utc)),
        ),
    ]
